### ISSUE TITLE
Have you used the the Azure Cloud+AI Icon Set?

### ISSUE THREAD

**Issue by smflorentino** [David-Summers/Azure-Design#1]
First, wanted to say thank you for such a great resource.
You mentioned in the description you imported SVGs into Visio's format, and that a complete collection in Visio format did not exist, and that some icons are missing.

I wanted to ask, have you also imported the SVGs from here? 
1) They might have the "missing" icons
2) I'm not an SVG expert, but they're drawn in such a way that you can change the color *within* Visio instead of requiring new icons to be generated.

https://www.microsoft.com/en-us/download/details.aspx?id=41937

**Comment by David-Summers** [comment]
Thank you for the comment, yes I have seen the CnE SVG icons, this prompted me to start this project in the first place as there were no visio versions of the icons. I know you can use SVG's in Visio, but I prefer actual visio stencil objects as I can script diagram creations by calling the object by it's master ID etc. They are also missing some services such as the cognitive services sub services like knowledge\speech etc. 

There are some icons that are there but not in mine and I might re-draw them in at some stage. If you feel there is a specific icon(s) that should be included then let me know
