### ISSUE TITLE
Blob Storage

### ISSUE THREAD

**Issue by tcwvdl** [David-Summers/Azure-Design#10]
Icon for Azure Blob Storage is missing.

**Comment by fmms** [comment]
I guess you are looking for the storage account?
![image](https://user-images.githubusercontent.com/908734/62836699-3433b200-bc66-11e9-812d-4869613e9919.png)

**Comment by tcwvdl** [comment]
I am not looking for the storage account, it's too generic. I prefer if you could select an icon from one of the storage types you can create with Azure Storage, like Blob, Table, File, or Queue. It will make the drawings you can make with this set more clear.

**Comment by David-Summers** [comment]
Hi @tcwvdl - I know what you were getting at, the sub-services were not included in the first version as there were no SVG versions available. Now that things have settled down I found time this morning to draw them. Queue, Table and Blob are now included in 1.3
