### ISSUE TITLE
Wrong color on Elastic Database Pools

### ISSUE THREAD

**Issue by deloorc** [David-Summers/Azure-Design#11]
Hi,

I could be wrong but I think the color in the Elastic Database Pools is not correct. 

Screenshot from the icon that is included in [ Microsoft_Cloud_AI_Azure_Service_Icon_Set_2019_09_11](https://www.microsoft.com/en-us/download/details.aspx?id=41937)

![image](https://user-images.githubusercontent.com/12133491/65794646-e2d57880-e168-11e9-9518-ffab2b8e4f7e.png)

When you have a look at [ICONS_Azure-Full-Colour_V-1.5.png](https://github.com/David-Summers/Azure-Design/blob/master/ICONS_Azure-Full-Colour_V-1.5.png) it will show some black on the database icons. This is also the case when used in Viso.

PS: Thanks for the effort in creating this stencil!

**Comment by David-Summers** [comment]
Thank you Cédric  - great pickup! I have corrected that in version 1.6
