### ISSUE TITLE
Icon Request: Azure Site Recovery/Azure Backup/Windows Virtual Desktop

### ISSUE THREAD

**Issue by liamfoneill** [David-Summers/Azure-Design#13]
Would be good to get these 3 added.

**Comment by xeeva** [comment]
Hi Liam, Azure Site Recover and Azure Backup both use the same icon. All my icons are named after the Azure service as displayed in the portal so you will find what you need under "Recovery Services Vault" which is the container service for both backup and ASR. WVD is a tricky one as there is no specific icon for that service that I can see. Closest match would be Host and Host Groups as WVD is essentially an RDS solution. If you find a decent image then ping it my way and I'll work on it

**Comment by liamfoneill** [comment]
Great thanks! I believe there will be a WVD logo coming out very soon when it is going to be integrated with Azure Portal. I'll close the issue for now.
