### ISSUE TITLE
Boxes Can Only Be Square

### ISSUE THREAD

**Issue by liamfoneill** [David-Summers/Azure-Design#14]
Thanks for adding the arrows and boxes - it really speeds up drawing things like VNET Boundaries quicker. However one thing I noticed is that the boxes are locked to be a square shape rather than a rectangle. I know with some shapes in Visio I can unlock width/height under Developer/Shape Design/Protection

Could you disable the "aspect ratio" option for all of the box shapes?
![image](https://user-images.githubusercontent.com/1243172/77520844-b4b3c580-6e79-11ea-961b-998610a5d080.png)

Repro: Drag "A_Box-1" shape to canvas. Try to drag either horizontal or vertical handle out.
Expected Behaviour: Shape can be height can be expanded independently of shape width

**Comment by David-Summers** [comment]
Hi Liam, this has been fixed in 2.6
