### ISSUE TITLE
Icon Search Instructions

### ISSUE THREAD

**Issue by liamfoneill** [David-Summers/Azure-Design#15]
Hi David,

Could you post some instruction on how you got the Icon Search to work? I have tried everything including in these two blog posts and still your icons don't show up in search.

https://eosfor.wordpress.com/2017/04/10/visio-2016-search-is-not-working/
https://eosfor.github.io/2018/another-visio-search-problem/

I noticed the stencils are in English (Australia) so I changed them to be English (United Kingdom) which is my display language but it had no effect :(

**Comment by TheFairey** [comment]
Also having this issue so dying for a solution :-)

**Comment by David-Summers** [comment]
So. Search. 

I now have a solution and I will update the readme in the next few hours (Version 3.1 release also)

So sorry for the lack of response but this has been a mission to resolve....

**Comment by David-Summers** [comment]
@liamfoneill  & @TheFairey 

3.1 has just dropped. Can you check out the updated readme for search and let me know if the suggestions work for you please

**Comment by TheFairey** [comment]
@David-Summers - Many thanks I can finally confirm search works and for me it was the ludicrous metrics setting.....everything else was already set bar the any words in Visio options but even with that set it took the metrics change for search to actual work.

Huge thanks especially as I can't zoom on the text of the icons so was having to guess half the time based on my experience.

Perfect timing as I now have an Azure diagram I need to do.

**Comment by David-Summers** [comment]
Awesome to hear :D I will close this now as I have had a few responses via Twitter that this change got search working. Apologies once again for the delay, but this has been a mission to resolve. Visio is just a little special when it comes to Search unfortunately.
