### ISSUE TITLE
Consider including a draw.io library in releases

### ISSUE THREAD

**Issue by CodeRunRepeat** [David-Summers/Azure-Design#18]
Visio is a prevalent tool, and yet some teams choose to use other diagramming tools such as [draw.io](https://draw.io). The Visio stencil can be easily transformed in a draw.io library by [importing it](https://desk.draw.io/support/solutions/articles/16000067790-how-to-create-and-use-custom-libraries-). Not aware of a programmatic way to do this but it's pretty easy to do manually. Sample file attached.

[AzureFullColor-DavidSummers.zip](https://github.com/David-Summers/Azure-Design/files/4574154/AzureFullColor-DavidSummers.zip)

**Comment by David-Summers** [comment]
On my list of new things. Maybe version 2.9
