### ISSUE TITLE
Incorrect name on Icon for Microsoft Forms

### ISSUE THREAD

**Issue by kilasuit** [David-Summers/Azure-Design#20]
The icon for Microsoft Forms is incorrectly names as O365 - Flow

![image](https://user-images.githubusercontent.com/6355225/92415902-e16f4700-f152-11ea-925c-96263900e04b.png)

From Microsoft 365 App panel 
![image](https://user-images.githubusercontent.com/6355225/92415929-f8ae3480-f152-11ea-939d-b198a844216e.png)

**Comment by David-Summers** [comment]
Thank you! - This has been updated in version 3 which is now live
