### ISSUE TITLE
How to download the latest release

### ISSUE THREAD

**Issue by MisterCloudTech** [David-Summers/Azure-Design#21]
The latest release seems very interesting, but going through the README page I cannot locate any instructions on how to download the content.
Is there a zip file anywhere with all the files in the latest release ?

**Comment by David-Summers** [comment]
Hi, all downloadable content is accessible from the root of my repo https://github.com/David-Summers/Azure-Design and you can download all of the content in one go by selecting code dropdown menu on the top right and then Download as Zip

![image](https://user-images.githubusercontent.com/53208734/99919860-b1a40880-2d6b-11eb-9db2-adbcc8160877.png)
