### ISSUE TITLE
Azure Active Directory App Proxy missing

### ISSUE THREAD

**Issue by Muxxx** [David-Summers/Azure-Design#31]
Hi David,

Can you please have the Application Proxy icon from Azure AD added. I cannot find it in your latest release (3.3).

Thanks!

**Comment by David-Summers** [comment]
Hi Stef, added for the next release. Thank you for pointing it out :D

**Comment by David-Summers** [comment]
Correction, this is actually in the stencil https://github.com/David-Summers/Azure-Design/blob/master/PNG_Azure_Grouped/Application/Application%20Proxy.png it is under the application category
