### ISSUE TITLE
Missing Connection Icon

### ISSUE THREAD

**Issue by drewkg** [David-Summers/Azure-Design#34]
I was searching the All Azure 3.5 for a connection icon (Microsoft.Network/connections) and could not see this, am I missing something?

**Comment by David-Summers** [comment]
Hi Keith do you have a specific example please? There are various objects within the Networking stencil that are used to depict connections to a VNET, NiC, Private Endpoint, Service Endpoint, Peering etc

**Comment by drewkg** [comment]
Hi David, I was looking for an icon to represent the resource for Microsoft.Network/connections, the closest I found eventually was the Express Route Connection icon which appears to be the same in Azure as the Connection icon.

This was to represent a connection within a S2S tunnel back to an on premises network, through a Local Network Gateway

**Comment by David-Summers** [comment]
Hi Keith 

Yes you are correct the Express Route connection icon is the same as the one displayed in the Connections blade and that is what I would use. Example below of how I would draw that type of configuration

![image](https://user-images.githubusercontent.com/53208734/119903226-c1571080-bf8b-11eb-8b3a-f9ad8caeec5c.png)

**Comment by drewkg** [comment]
Hi David,

Thank you for the confirmation, and the nice clear example of how you would diagram the type of connection it is appreciated to see.

I did use the Express Route connection icon.  Feel free to close this issue as it is resolved in my mind.
