### ISSUE TITLE
Drawing-Tools file shows up as All-icons

### ISSUE THREAD

**Issue by SvenAelterman** [David-Summers/Azure-Design#36]
When opening the file `Azure_Drawing-Tools_V-3.6.vssx`, it is listed in the Stencils as `Azure_All-icons_V-3.6`.

**Comment by David-Summers** [comment]
Hi Sven

I will correct this mistake on the next release. Thank you once again

Dave

**Comment by David-Summers** [comment]
Corrected in version 3.7
