### ISSUE TITLE
icon request: icons from Azure  Data Factory

### ISSUE THREAD

**Issue by jikuja** [David-Summers/Azure-Design#40]
Split from #39 

Azure Data Factory contains a set of icons that are not yet available in your stencil set:
* (creation of) integration runtime has the following icons:
  * generic integration runtime icon
  * Azure SSIS icon
  * Azure integration runtime icon
  * Self-hosted integration runtime icon
  * linked integration runtime icon
* (creation of) linked services probably contain some icons that are missing
  * snowflake
  * second data lake gen2 icon
  * probably others
* Other internal data factory resources. For this group, colored versions are available only when creating a new resource on portal
  * pipeline
  * dataset
  * dataflow
  * power query
  * directory for consistent styling (colored version unavailable?)
  * maybe template

Sadly those icons are embedded on TBD requires extracting with browser developer tools.

**Priority:**
* **Integration runtimes, data lake, and snowflake.** Those icons have high usability value for architectural design documents
* other linked services
* remaining data factory resources

Please let me know if you need any help finding those icons from the portal. I have saved the highest priority already locally and could share them if needed.

**Comment by David-Summers** [comment]
Not a problem. If you have SVG versions of the icons then attach them here while I work on the remaining ones

**Comment by jikuja** [comment]
[azure-svgs.zip](https://github.com/David-Summers/Azure-Design/files/7289541/azure-svgs.zip)

**Comment by David-Summers** [comment]
Thanks for the challenge hahaha

I will need to draw most of those so might not be in the next release. If you have image examples (any format is fine) then send them through and I can design new SVG icons for them

**Comment by David-Summers** [comment]
Good news is the double click to edit is fairly straight forward

Application.ActiveWindow.Page.Shapes.ItemFromID(10).CellsSRC(visSectionObject, visRowEvent, visEvtCellDblClick).FormulaU = "OPENTEXTWIN()"

Just need to convert the above VBA to PS which is fairly easy

**Comment by David-Summers** [comment]
[TEST_V3.8.zip](https://github.com/David-Summers/Azure-Design/files/7289772/TEST_V3.8.zip)

Could you test the double click behavior in the attached please

**Comment by jikuja** [comment]
Works for me.
