### ISSUE TITLE
Icons request: AKS

### ISSUE THREAD

**Issue by SvenAelterman** [David-Summers/Azure-Design#43]
AKS has many "child" resources, such as workspaces, node pools, and services that might be useful to represent in diagrams.

**Comment by SvenAelterman** [comment]
Here are a few of the SVGs
[AKS.zip](https://github.com/David-Summers/Azure-Design/files/8017998/AKS.zip)
.

**Comment by David-Summers** [comment]
Added in 4.0, thank you for supplying the Icons :D
