### ISSUE TITLE
Icons request: Policy Assignment & Initiatives

### ISSUE THREAD

**Issue by drewkg** [David-Summers/Azure-Design#45]
I might be missing something, but whilst I can find the icon for Azure Policy the following do not appear to be in the Azure Management pack

Policy Initiative
Policy Assignment
Policy Exception

I am currently reusing the Policy Icon, which can prove to be confusing.

**Comment by David-Summers** [comment]
Thank you!

Adding to tonight's build 4.1 along with a few more
