### ISSUE TITLE
Make TxtPinY value dynamic to accommodate resizing of icons

### ISSUE THREAD

**Issue by alwortma** [David-Summers/Azure-Design#47]
The default value for TxtPinY seems to be -14mm, which means scaling the icon up or down causes the text box to drift up into, or far away from the icon.

I modified the value to **_-(Height*0.7)_**, which seems to allow the text box to stay in a better position when scaling the icons.

![image](https://user-images.githubusercontent.com/97995966/163652591-8e04eb96-a426-46a3-8b0a-f8a6e27a0d18.png)

**Comment by David-Summers** [comment]
Hi there. Which stencil version was that? as I have had a dynamic value in there for a while. 

My Stencil build script uses these values, so your example on the right should have had a value of "Height*-0.25" not -14mm

            $Shape.CellsU("TxtWidth").FormulaU = "TEXTWIDTH(TheText)"
            $Shape.CellsU("TxtHeight").FormulaU = "TEXTHEIGHT(TheText,TxtWidth)"
            $Shape.CellsU("TxtPinX").FormulaU = "Width*0.5"
            $Shape.CellsU("TxtPinY").FormulaU = "Height*-0.25"
            $Shape.CellsU("TxtLocPinX").FormulaU = "TxtWidth*0.5"
            $Shape.CellsU("TxtLocPinY").FormulaU = "TxtHeight*0.5"
