### ISSUE TITLE
Network Security Group is missing since 3.8

### ISSUE THREAD

**Issue by SvenAelterman** [David-Summers/Azure-Design#48]
Network Security Group (classic) is still in the stencils and image files, but the "current" NSG icon is missing.

I am attaching it here for reference:
![Network security group](https://user-images.githubusercontent.com/17446043/176035109-38ef871e-7074-40d9-830b-305908f01bc9.svg)

**Comment by David-Summers** [comment]
Hi Sven, it is there but classified under Security. Changing the category to Networking for consistency in 4.2
