### ISSUE TITLE
Awesome set of Azure Icons, but missing Virtual Hub

### ISSUE THREAD

**Issue by bcosden** [David-Summers/Azure-Design#49]
The icon set is fantastic and more useful than the default ones in Visio. Pretty much all of them I need are there. But noticed that Azure Virtual Hub (inside of Azure Virtual WAN) is missing. Is that on the radar to create? It looks like this: 
![image](https://user-images.githubusercontent.com/27424423/179994674-90c58a4a-dace-4582-b2b2-2915705f4a3e.png)

There is also a secured hub version that looks similar but is red.

**Comment by SvenAelterman** [comment]
@David-Summers Here's the SVG:
![vWAN Virtual Hub](https://user-images.githubusercontent.com/17446043/180103446-5681cf1c-c8b5-42db-a893-7511a0b32998.svg)

**Comment by David-Summers** [comment]
Thank you again, included with 4.3 which just released
