### ISSUE TITLE
Add App Service Access Restriction and App Assigned Address

### ISSUE THREAD

**Issue by SvenAelterman** [David-Summers/Azure-Design#50]
Icons attached in SVG.
App Service Access Restriction: <img src="https://user-images.githubusercontent.com/17446043/180102899-fdfb66cc-1c16-4e16-911c-15db9024d33a.svg" width="144px" />
App Service App Assigned Address: <img src="https://user-images.githubusercontent.com/17446043/180102981-d0a27874-abc2-4b39-94e2-9c24b3acb37c.svg" width="144px" />

**Comment by David-Summers** [comment]
Thank you as always Sven. Included with 4.3 which just released
