### ISSUE TITLE
Make all icons square

### ISSUE THREAD

**Issue by fmms** [David-Summers/Azure-Design#52]
Hi,

in you postprocessing an creation of SVG files it would be very nice if all icons would be square and same size.
Have a look at the following behaviour in PowerPoint. One can just drag&drop the SVG files there.

![image](https://user-images.githubusercontent.com/908734/188288878-64a921db-ce2a-4240-a163-87b27bc917e1.png)

- The Power BI and Data Lake icon have lots of white space at the bottom.
- The Azure Analysis Services icon seems to be bigger than the one of Azure SQL Database.

Thanks

**Comment by David-Summers** [comment]
Hi Olav, this should be fixed now in version 4.3 which just released. Was fun to do, as the current versions of inkscape do not process verbs, so doing something like "--verb=FitCanvasToDrawing --verb=FileSave --verb=FileQuit" as a batch process did nothing. Figured out a work around though.
