### ISSUE TITLE
Icon for Log Analytics Workspace and AVD Workspace are not correct.

### ISSUE THREAD

**Issue by marcelbraak** [David-Summers/Azure-Design#55]
AVD Workspace Icon is named as Log Analytics Workspace
Log analytics Workspace icon is missing

**Comment by SvenAelterman** [comment]
Agreed. This was also in 4.2.

For reference, adding the correct SVG icons for both services.
Log Analytics Workspace: ![00009-icon-service-Log-Analytics-Workspaces](https://user-images.githubusercontent.com/17446043/214980691-09337480-106f-40fc-aa41-379f46f3b801.svg)
AVD Workspace: ![00330-icon-service-AVDWorkspaces](https://user-images.githubusercontent.com/17446043/214980790-b8c6ed53-6346-4468-88e4-137711ac8cf5.svg)

**Comment by David-Summers** [comment]
Updated for the next release. Thank you! I have a bit of a backlog to work through, hopefully I will have some free time this weekend to release.

**Comment by marcelbraak** [comment]
Any update on the expected release date?

**Comment by David-Summers** [comment]
Main build is done for the next release, still working on this issue though

https://github.com/David-Summers/Azure-Design/issues/54 

in the next few days

**Comment by David-Summers** [comment]
Resolved in version 4.4 which just released
