### ISSUE TITLE
Missing Icon for API Management Service Gateway

### ISSUE THREAD

**Issue by stefandoh** [David-Summers/Azure-Design#56]
Great job overall - just noticed on drawing that the latest symbol for API Management Service Gateway is not included.

**Comment by David-Summers** [comment]
Thank you Stefan!

Added in the next release along with ~50 new icons. I have a bit of a backlog of other issues to work through before releasing though. Hopefully I will have some spare time this weekend

**Comment by stefandoh** [comment]
Amazing Job, David! Thanks :)

**Comment by stefandoh** [comment]
Will be added in the next release. Closed.
