### ISSUE TITLE
Missing Shape for App Service API

### ISSUE THREAD

**Issue by johnavery** [David-Summers/Azure-Design#57]
Hello, first off, great library, thank you for your great work!

In the Microsoft Azure Cloud Icons stencil, there is an "API App" shape.  I see you have an "App Service API Definition" shape, but no "App Service API" counterpart, which would in my mind be the equivalent of the MS API App shape.  

In comparison, you have both an (API Management) "API definition" shape, and an "API Management API" counterpart shape.  It would be great if we had this for App Services too!

I would think that an App Service API shape would look similar to the App Service API Definition shape, but without the lines below that denote the "Definition" concept.

Again, great work, thank you for creating it!  If I've overlooked this shape somewhere in your stencil, please let me know.

**Comment by David-Summers** [comment]
Something like this?

![image](https://user-images.githubusercontent.com/53208734/219515670-eb9cda85-1164-4fc5-80ff-838c9761ccc7.png)

**Comment by johnavery** [comment]
Now that I've taken a closer look, I think it would essentially be the same shape as your API Management API shape, which is this:

![image](https://user-images.githubusercontent.com/24736576/219681696-8f6c174e-5cc3-4fa3-907e-87d9e7ec1bfa.png)
 
But named as App Service API.  Not sure if you think it's worth it.  You kinda did the same thing with the two definition shapes.  Same shape, different name.  I personally think there's value in it, as it makes it clear to the consumer who's looking for a specific shape for a specific concept.  Up to you.

**Comment by johnavery** [comment]
Existing example pairs:

API Management Service and App Service API Management
API Definition and App Service API Definition

(sorry, couldn't upload the images for some reason)

**Comment by David-Summers** [comment]
Hi @johnavery 

Added this in version 4.4 which just dropped

https://github.com/David-Summers/Azure-Design/blob/master/SVG_Azure_All/App%20Service%20API.svg
