### ISSUE TITLE
Remove shadow effect

### ISSUE THREAD

**Issue by bastienperez** [David-Summers/Azure-Design#59]
Hello,

First of all, thanks for you work !

Is there a quick way to remove the shadow for all the shapes without modify each shape?

Is there a quick method to remove the shadow effect from all shapes without having to adjust each one individually?

Thanks.

**Comment by ismailgiles** [comment]
I have the same issue.  The shadows don't work well with Lucidchart, so I need some way to remove them.

**Comment by David-Summers** [comment]
Hi Bastien

I have been debating this with the community and I dcided to remove the drop shadow. It was a personal preference of mine, but the masses voted. Will be releasing a version 4.6 later today that removes the shadow.
