### ISSUE TITLE
Remove the Azure prefix for all ressources

### ISSUE THREAD

**Issue by fmms** [David-Summers/Azure-Design#6]
Hi,

I think the Azure prefix should be removed from all icons, or is there any reason to it?
E.g. why is it "SQL Database" / "Analysis Services" and "Azure Data Factory" / "Azure Function".

regards
Felix

**Comment by David-Summers** [comment]
Good pickup, I was matching names with the actual Azure services. Dropped the Azure prefix on 6 incorrectly named icons, version 1.2 uploading later today
