### ISSUE TITLE
Rename "Azure AD" with "Entra ID"

### ISSUE THREAD

**Issue by kaiaschulz** [David-Summers/Azure-Design#61]
A while ago, Microsoft announced the renaming of the Azure Active Directory:
[New name for Azure Active Directory](https://learn.microsoft.com/en-us/entra/fundamentals/new-name)

Regarding to this, please rename the Visio shapes as well :)

Thanks a lot.
Have a nice day.

**Comment by David-Summers** [comment]
Howdy

Yes, version 4.6 includes all the Entra renamed services. Have been working on this for a while and will drop the next release in a few hours
