### ISSUE TITLE
Plans to publish the scripts

### ISSUE THREAD

**Issue by itpropro** [David-Summers/Azure-Design#62]
Hi,
I really like the outcome of svgs and stencils in this repo. It would be very helpful, if the actual scripts und tools used to extract these icons and extract/reformat them would also be available, so that everyone could pull the SVGs themselves if there are updates.

To avoid having to pull the whole repository, the current version could automatically be published as releases for everyone to directly consume.

**Comment by David-Summers** [comment]
Hi there Jan-Henrik

Unfortunately it is not that simple, my core script works on pre-downloaded / created SVGs and automates the creation of the Stencils, PNGs and SVGs. My update process involves visually checking new services, sourcing the icon, verifying if it can be imported into Visio and correcting elements of the icon if the import fails (sometimes have to re-draw the icon if there are issues importing, you might notice on other Visio Icon repos that Icons look completely wrong with weired scaling issues on some icon elements) as well as new ones, I also visually scan everything looking for refreshed versions relying on memory for what I already have). This is a large amount of effort on my part and I wish I could script that component, but it is what it is.

**Comment by itpropro** [comment]
Hey David,
Thanks for detailing that! I wasn’t aware that there was so much manual work involved, it makes me appreciate this repository even more.
My main intention was to share any prebuilt/tested logic in scripts or source code that would help people that face a similar problem to generate and export stencils as well as SVGs as done with the ones here.
