### ISSUE TITLE
Should "PowerApps" be included?

### ISSUE THREAD

**Issue by fmms** [David-Summers/Azure-Design#8]
Hi,

i know this is more an Office 365 than Azure logo. However, you have Power BI in this icon set as well.

PowerApps: https://psuxemea.azureedge.net/Content/retail/assets/PA_logo.b7daae25b7fbb8372a8ea03e2cfdaaee.2.svg
Microsoft Flow : https://psuxemea.azureedge.net/Content/retail/assets/flow_logo.53055f6d0ed0d948806033a53b82197d.2.svg 

You see all these logos on the bottom of https://flow.microsoft.com/de-DE/ .

Thanks

**Comment by David-Summers** [comment]
Hesitant at this stage to include other o365 products (Mainly due to time, as I maintain this outside of working hours) I only included PowerBi as PBI Embedded is an Azure service offering. If there is enough interest I will consider a full o365 stencil suite separate to this one
