### ISSUE TITLE
PowerShell script

### ISSUE THREAD

**Issue by fmms** [David-Summers/Azure-Design#9]
Hi,

could you add your Power Shell script to collect the icons as well?
I think it would be very interesting to see where the different icons are collected from and how the visio stencil is created in the end.

There might even be room for improvement such as finding better places to attach the connectors to depending on the logo...

Is it a list of URLs you are iterating over to grab all SVGs or how does that work?

regards

**Comment by jachin84** [comment]
I'm also interested in looking at the script as well.

**Comment by David-Summers** [comment]
Hi, thanks for the offer for review. Unfortunately there is no script that generates the icons 100%. I use a combination of 2 scripts and a very manual process to extract the <G></G> content from an SVG and convert any classes to static values, load into an SVG editor change the scale to a fixed size, add metadata save. I then drop the SVG into my visio stencil builder, scale the icon and add 5 connection points randomly, name each point in the developer shape sheet and drop into my master stencil.

The script then iterates through the master stencil, changes the text field, moves the connection points, orders by name and drops each onto a page for saving as a PNG and inserts into the new stencil
